### ISSUE TITLE
start-ros-node not taking $ROS_IP into account

### ISSUE THREAD

**Issue by fairlight1337** [ros/roslisp#11]
I just realized that, when starting a ROS node using
```lisp
(roslisp-utilities:start-ros-node)
```
the environmental variable `$ROS_IP` is not taken into account for generating the RPC Caller URI. When only setting my `$ROS_IP` to my ethernet address (i.e. 192.168.0.1), I get the following when executing `roswtf`:
```
ERROR: Unknown host [] for node [/nodename]
```
Similarly, when publishing something from that node, I get the following `rostopic info` output:
```
$ rostopic info /nodename/sometopic
Type: visualization_msgs/MarkerArray
Publishers: 
 * /nodename (http://:51309)
```
but the published messages never reach any other node on the same ROS master (which is definitely set corretly).

When setting `$ROS_HOSTNAME` to the same value (have only tried setting it to an IP, as my hostname sometimes changes due to DNS/DHCP weirdry), everything works as expected:
```
$ rostopic info /nodename/sometopic
Type: visualization_msgs/MarkerArray
Publishers: 
 * /nodename (http://192.168.0.1:51309)
```
and other nodes get my published messages.

So my guess would be, that something is wrong in `roslisp/src/node.lisp`, somewhere in `start-ros-node`.

`$ROS_IP` should be usable for this purpose, shouldn't it? My `$ROS_HOSTNAME` was definitely not set before.

**Comment by gaya-** [comment]
@fairlight1337, is this still an issue? I've never encountered this problem on 14.04 and I never export my `ROS_HOSTNAME`.

**Comment by gaya-** [comment]
I have been using roslisp with remote master for a while now and never encountered this problem. I was using Ubuntu 14.04 ROS indigo. I never set `$ROS_HOSTNAME`. I do always set `$ROS_MASTER_URI `and `$ROS_IP`. In `roslisp` I don't give any additional parameters to `start-ros-node` except the node name.
@fairlight1337 does this issue still happen to you?

**Comment by fairlight1337** [comment]
Chew, 3 years. No, not recently; but I also always set both parameters (since otherwise service calls can cause trouble).

I'd say if I'm the only one that had that, let's close the issue. If it comes up again, someone might have an actual case on this.

**Comment by gaya-** [comment]
Yeah, this issue can be reopened if it comes up again.
But on modern versions of Linux and ROS (although 14.04 is not that modern anymore) it does not seem to be a problem.
You were using 12.10 back then which was not an LTS, I suspect there was a little bug in ROS that triggered this issue.

**Comment by fairlight1337** [comment]
I'm using 14.04 LTS and nothing bad is happening here. So yeah, I agree; I'll close it then.
