### ISSUE TITLE
ros-time gives different timestamp than rosccp's ros::Time::now

### ISSUE THREAD

**Issue by airballking** [ros/roslisp#22]
I ran into an inconsistency of timestamps on our robot: I get a timestamped message from a roscpp-node. Upon receipt, I call ```(roslisp:ros-time)```. I print both stamps, and the roslisp timestamp is older than the one from roscpp. This seems like a bug to me.

I checked that both my roslisp-node and my roscpp-node run on the same computer and that ```use_sim_time``` is set to false on the ROS parameter server. This relates to roslisp version 1.9.17 on ROS Hydro, Ubuntu Precise.

I looked into how roslisp implements its time mechanism. I am doubtful whether the two global variables ```*time-base*``` and ```*internal-time-base* ``` used for calculating the stamp refer to the same moment in time. If they do not, than the timestamp could be wrong by as much as +-1s. 
https://github.com/ros/roslisp/blob/master/src/time.lisp#L46

Are there alternatives in SBCL to ```(get-internal-real-time)``` which give us a real-time with respective to a globally known reference time? Or should we consider wrapping the c-functions for accessing the sys-time?

**Comment by gaya-** [comment]
> Or should we consider wrapping the c-functions for accessing the sys-time?

If you just want the equivalent of C system time in SBCL (you mean the one that comes from the operating system in milliseconds from the epoch, is that correct?) try the [```(sb-ext:get-time-of-day)``` from the unix API](https://github.com/sbcl/sbcl/blob/master/src/code/unix.lisp#L1087).

My guess is that, originally, roslisp developers tried to keep it as Lisp-compiler-independent as possible, so they used general Common Lisp functions and most of them work on seconds neglecting milliseconds, so you have to get the milliseconds from the run-time and who knows if it creates an overhead etc.

**Comment by airballking** [comment]
Oh, that is a cool hint! I was not aware of that functionality. 

Then the question is: Do we embrace such an sbcl-specific fix of ```(ros-time)```?

**Comment by gaya-** [comment]
My guess might also be wrong, because, now that I look closer, right inside the same ```(ros-time)``` function there is a call to ```(mutex-owner *debug-stream-lock*)``` which is an SBCL-specific function. So, if you try the ```get-time-of-day``` and it turns out to work better than ```get-universal-time``` I wouldn't object to using it instead...

**Comment by moesenle** [comment]
Right. roslisp is already very SBCL specific. Porting it to other Lisp
compilers would be quite some effort. I would just go ahead and use
whatever SBCL function fixes the problem.

Btw. if you don't want to change the official release, you can also think
about monkey-patching roslisp.

**Comment by gaya-** [comment]
@airballking Any update on this? I've noticed problems with cl-tf timestampes before, if sbcl time function solves the problem that would be nice. Have you tested this yet, Georg?

**Comment by airballking** [comment]
@gaya- I meant to but haven't got around to it. I'm prioritizing hardcore because of the upcoming review. Maybe I feel like checking this out over night. 

But you are right, this could be the source of "all those error in cl-tf:lookup-transform". I had not even considered this!

**Comment by gaya-** [comment]
https://github.com/ros/roslisp/pull/24 should solve this.

**Comment by airballking** [comment]
Fixed through Gaya's pull request.
