### ISSUE TITLE
add_lisp_executable fails if bin dir is not deployed

### ISSUE THREAD

**Issue by bbrieber** [ros/roslisp#27]
the CMake Macro add_lisp_executable fails with the message Directory nonexistent if there is no target-dir in the catkin_ws/devel/lib/<package_name> directory

**Comment by airballking** [comment]
@bbrieber I do understand your sentence. Could you please provide more explanations of the problems, or (even better) a repository with a minimal code example that brakes when calling ```catkin_make```. Thanks!

**Comment by bbrieber** [comment]
@airballking  it seems to be a bug in the tutorial from the ros wiki. The add_lisp_executable call should not have any directories specified for the executable name (like bin/talker).

We will correct this in the wiki now.

**Comment by airballking** [comment]
Alright.
