### ISSUE TITLE
Problem with installation on Mac OS El Capitan

### ISSUE THREAD

**Issue by ameerhamzakhan0310** [ros/roslisp#30]
I am installing ROS Indigo distro on Mac OS El Capitan using instructions given [here](http://answers.ros.org/question/224956/no-definition-of-procps-for-os-osx/). But when I run:
`rosdep install --from-paths src --ignore-src --rosdistro indigo -y`
I get the following error:

> ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
roslisp: Missing resource geneus

Is there any way to resolve this?

**Comment by airballking** [comment]
Corresponding ROS Answers question:
http://answers.ros.org/question/224521/roslisp-missing-resource-geneus/

**Comment by ameerhamzakhan0310** [comment]
That question was also asked by me, but still there is no answer.

**Comment by airballking** [comment]
Personally, I have never used MAC OS. Also, I am puzzled about the dependency on ```geneus```. There is ```ros-indigo-geneus``` but that is the integration for a different LISP. We doe not depending on that version. 

Could you try figuring out the dependency chain? What does this print out:
```rosdep keys roslisp```

@gaya- @bbrieber @fairlight1337 any idea?

**Comment by ameerhamzakhan0310** [comment]
This command produceed following output:

> ERROR: Rosdep cannot find all required resources to answer your query
Missing resource roslisp

Although i worked around the initial problem using [this](http://answers.ros.org/question/224956/no-definition-of-procps-for-os-osx/). But still there are problems in later stages. I think it is better to use it on a Linux VM.

**Comment by airballking** [comment]
@ameerhamzakhan0310 Is this still an issue? Did you make progress towards a solution?

**Comment by ameerhamzakhan0310** [comment]
No, I switched to Linux version of ROS.

**Comment by airballking** [comment]
OK. Wish you max success with ROS! :)
