### ISSUE TITLE
MAKE-MESSAGE also accepting symbols for specifying message type

### ISSUE THREAD

**Issue by gaya-** [ros/roslisp#32]
Currently, it only accepts strings.
Would be nice to add symbol support, just like, e.g., in MAKE-REQUEST.

**Comment by airballking** [comment]
Could you please give an explicit example of what you'd like to have? Thanks.

**Comment by gaya-** [comment]
Gladly. I'll give an example together with a PR.

**Comment by gaya-** [comment]
Please see an example in https://github.com/ros/roslisp/pull/35

**Comment by gaya-** [comment]
Solved in #35
