### ISSUE TITLE
Error loading roslisp on newer SBCL versions

### ISSUE THREAD

**Issue by sjlevine** [ros/roslisp#41]
Hello,

First of all, let me thank you for your hard work on this very useful project!

I'm having trouble running `roslisp` on recent versions of SBCL. Specifically, when I run the following to  load roslisp:

```lisp
;; Trick to load roslisb-sbcl-init
(load (concatenate 'string
                   (string-trim '(#\Newline) (asdf/run-program:run-program '("rospack" "find" "roslisp") :output :string))
                   "/scripts/roslisp-sbcl-init"))

;; Load roslisp -- gives below error
(ros-load:load-system :roslisp)
```

I get the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-IMPL violated when interning *DEADLINE-SECONDS* while in
;     package ROSLISP-UTILS.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 259, column: 0, position: 8512)

; compilation aborted after 0:00:00.037
```

I'm no expert on the internal workings of `roslisp`, but I have a hunch what could be going on. Here, roslisp makes use of `sbcl-impl:*deadline-seconds*`:
https://github.com/ros/roslisp/blob/3aeebb36d808937ecffac8f6e43eb66d35caf1ef/utils/utils.lisp#L265

This seems to be because SBCL's sleep does not respect deadlines (according to the comment several lines above).

In December 2017, it looks like the `*deadline-seconds*` symbol was removed in SBCL by [this commit](https://github.com/sbcl/sbcl/commit/5dcd65cfcf16f3331a561ef1944fc75a29e7e609#diff-1a36bc3eccca9108fd2589a09f8b2626). Furthermore, based on [this commit](https://github.com/sbcl/sbcl/commit/27f2f75b4e1df8364e6c89fd40b5d72f9b83425e#diff-1a36bc3eccca9108fd2589a09f8b2626) a few days later, it seems that SBCL's sleep does now support deadlines.

(I tested on SBCL 1.4.10, but theoretically this should apply to the past few versions).

Any advice would be very much appreciated. Thanks again!

**Comment by gaya-** [comment]
Yes, I am aware of this problem but, unfortunately, I did not have time to look into this deeply. I did notice that they got rid of ``*deadline-seconds*`` but did not know that sleep doesn't require it anymore, it does look like that from your last link. Thanks a lot for the info! There are some other changes in the compiler that break stuff, unfortunately. For now, you could install an older version of SBCL, it's very easy, just download the tar, extract the files and run the install script. I know that roslisp works well with [SBCL 1.3.1](https://sourceforge.net/projects/sbcl/files/sbcl/1.3.1/) (I use x86-64 binary) on Ubuntu 14.04 and Ubuntu 16.04, so hopefully 18.04 will also be fine. I'll look into this issue after the ICRA deadline mid September, no time before that, sorry :(. If you could provide a PR I would be glad to test and merge it asap.

**Comment by sjlevine** [comment]
Thank you very much for the fast response! Indeed I am following exactly your advice: SBCL 1.3.21 is working fine for me. I also have some thesis-related deadlines coming up so I will likely not have time to dive deeper for a pull request either in the next few weeks. Thanks again!

**Comment by gaya-** [comment]
Fixed in https://github.com/ros/roslisp/commit/2489f38aac6a3b7a085f14bb86601653001c5245. Tested on Ubuntu 18.04 with ROS Melodic, SBCL version 1.4.5.
