### ISSUE TITLE
[noetic] Uses python on Buster when ROS_PYTHON_VERSION is 3

### ISSUE THREAD

**Issue by sloretz** [ros/roslisp#42]
It looks like `roslisp` tries to use `python` on Debian Buster. [PEP 394](https://www.python.org/dev/peps/pep-0394/) says `python` could be any version, and on Buster it's Python 2.

I found this by deleting the `python` executable in a docker container. When sourcing another package it showed:

```
/home/sloretz/rsp_ws/devel_isolated/robot_state_publisher/env.sh: 1: /home/sloretz/ws/noetic/devel_isolated/roslisp/etc/catkin/profile.d/99.roslisp.sh: python: not found
```

The problem seems to be here.

https://github.com/ros/roslisp/blob/efa052c4d33abcbe190450ce54a82c0c34160d3a/env-hooks/99.roslisp.sh#L21

One fix might be to add an `<exec_depend>` on [ros_environment](https://github.com/ros/ros_environment) and use `python${ROS_PYTHON_VERSION}`. I don't think that would work on Windows though.

**Comment by airballking** [comment]
@sloretz Thanks for reporting this! Is Windows actually a target platform for Noetic?

@gaya- Shall we try the suggested fix for Debian & Ubuntu versions?

**Comment by gaya-** [comment]
@airballking Sure, go ahead.

**Comment by sloretz** [comment]
> Thanks for reporting this! Is Windows actually a target platform for Noetic?

I don't think it will be a target platform in REP 3, though I assume `roslisp` works on windows in Melodic already. It's part of `desktop_full`, and [the Windows install instructions mention `desktop_full`](http://wiki.ros.org/Installation/Windows#Stay_Up_to_Date).

@seanyen If you don't mind me asking, do you know of a solution that would work on Windows too? If you do, it might be relevant to solving ros/ros_comm#1830 too.

**Comment by seanyen** [comment]
> @seanyen If you don't mind me asking, do you know of a solution that would work on Windows too? If you do, it might be relevant to solving [ros/ros_comm#1830](https://github.com/ros/ros_comm/issues/1830) too.

I haven't very closely looked into Python3 compatible with ROS on Windows yet, but let me see if I can find some time this week taking a look of that.

**Comment by airballking** [comment]
@seanyen Thank you for your offer to help! I appreciate it. :)
