### ISSUE TITLE
Noetic Release?

### ISSUE THREAD

**Issue by sloretz** [ros/roslisp#47]
Mind releasing this repo into Noetic? It looks like all dependencies of packages in this repo have been released already. `roslisp` appears to be recursively blocking 484 others.

http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22roslisp%22&s=6&r=1

**Comment by gaya-** [comment]
I will merge the PRs on Monday or over the weekend. Sorry for the delay.
Should I initiate the Noetic release? Previously, roslisp was always released together with the rest of ROS by the open robotics team. But I can do it too, I don't mind.

**Comment by sloretz** [comment]
> Should I initiate the Noetic release? 

Yes please!

> Previously, roslisp was always released together with the rest of ROS by the open robotics team. But I can do it too, I don't mind.

I didn't realize we've been releasing it. I assumed it was always one of the maintainers listed in a `package.xml` in the repo.

**Comment by gaya-** [comment]
Meh, I don't know how to release into different distros from different branches properly, so I ended up having different tags. Feels like a hack to me and there is probably a more elegant solution but I guess it will do for now.
The PRs to rosdistro are out.

**Comment by sloretz** [comment]
Thank you for https://github.com/ros/rosdistro/pull/23797 !
